name: ebazaar
description: "Flutter E-commerce application"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  image_cropper: ^6.0.0
  connectivity_plus: ^6.0.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.10

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.2.2+2


#--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/user/
    - assets/icons/brands/
    - assets/icons/system/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  flutter_native_splash:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/e-bazaar-logo-black.png
    image_dark: assets/logos/e-bazaar-logo-white.png

    android_12:
      color: "#FFFFFF"
      color_dark: "#272727"
      image: assets/logos/e-bazaar-logo-black.png
      image_dark: assets/logos/e-bazaar-logo-white.png

    web: false