name: ebazaar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  logger: ^2.0.2+1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/user/
    - assets/icons/brands/
    - assets/icons/system/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/on_boarding_images/
